# Generated by Django 5.2 on 2026-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lliga',
            options={'verbose_name': 'Lliga', 'verbose_name_plural': 'Lligues'},
        ),
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default='Barcelona', max_length=100),
            preserve_default=False,
        ),
    ]
