# Generated by Django 5.2 on 2026-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0002_alter_lliga_options_equip_ciutat'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='edat',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
