# Generated by Django 5.2 on 2026-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0003_jugador_edat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lliga',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
