# Generated by Django 5.2 on 2026-02-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0004_lliga_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lliga',
            old_name='date',
            new_name='data',
        ),
    ]
